name: Generate DOCX with Pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Specific Version of Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-1-amd64.deb
        sudo dpkg -i pandoc-2.11.4-1-amd64.deb

    - name: Install Fonts
      run: |
        sudo apt-get install -y fonts-dejavu fonts-liberation
        # Add any other fonts you need here

    - name: Generate DOCX
      run: pandoc -s --toc --toc-depth=3 --metadata title="Master Hyper-V" --metadata author="Marc Mylemans" -o MasterHyper-V.docx --reference-doc=template.docx $(cat book-order.txt)

    - name: Upload DOCX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: MasterHyper-V.docx
        path: MasterHyper-V.docx

    - name: Get the current date and time
      id: vars
      run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.0
      with:
        tag_name: v${{ env.date }}
        release_name: Release v${{ env.date }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.1.0
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MasterHyper-V.docx
        asset_name: MasterHyper-V-${{ env.date }}.docx
        asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
